services:
  n8n:
    build: .
    container_name: n8n
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n
      # - C:\Users\user\Dev\n8n_files:/home/node/files FOR WINDOWS
      - /n8n_files:/home/node/files
    ports:
      - 5678:5678
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      # - N8N_HOST=dockernode1localhost.internal.com
      - WEBHOOK_URL=${N8N_WEBHOOK_URL} #http://dockernode1localhost.internal.com:5678
      - N8N_PROXY_HOPS=1

volumes:
  n8n_data: {}
